spring.application.name=footwear-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/footwear_shop
spring.datasource.username=postgres
spring.datasource.password=ROOT1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


